name: Generate PHP client
on:
  workflow_dispatch:
  push:
    paths:
      - 'openapi.json'

jobs:
  generate-php-client:
    runs-on: ubuntu-latest
    name: Generate PHP client
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate PHP Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-file: openapi.json
          command-args: --output=./

      - name: Update PHP Client
        run: |
          git config --global user.email "amplexor.belgium@gmail.com"
          git config --global user.name "MPPlexor"
          ls -la
          git status
          git diff
          git add
          git status
          git diff
          git commit -am "Update PHP Client"
          git push
